### PR TITLE
2255201069_ikhsanconflict

### PR DESCRIPTION
**Pull request by Ikhsan-Sigma**
WIN_20241021_12_20_39_Pro

### CODE REVIEW

**Review by nabilaauliaputrihardiansyah — CHANGES_REQUESTED** [review]
ubah oi

**Comment by Ikhsan-Sigma** [comment]
ok bg

**Review by nabilaauliaputrihardiansyah — CHANGES_REQUESTED** [review]
ooppppp

**Review by nabilaauliaputrihardiansyah — CHANGES_REQUESTED** [review]
ubah lagi isan

**Review by nabilaauliaputrihardiansyah — CHANGES_REQUESTED** [review]
di ulang

**Pull request closed without merging**
